language: php

php:
  - "7.2"

install:
  - ./scripts/composer.sh install --no-interaction

script:
  - ./scripts/print-info.sh
  - ./scripts/phpunit.sh --whitelist ./other --coverage-clover ./other/clover.xml

after_success:
  - travis_retry ./scripts/coveralls.sh -x ./other/clover.xml
